package network.model;

public enum MessageType {
    WELCOME,
    CONNECTION_ACCEPTED,
    CONNECTION_REFUSED,
    REQUEST_NODE_INFO_TABLE,
    NODE_INFO_TABLE,
    USER_MESSAGE,
    ACKNOWLEDGE,
    BROADCAST,
    DUPLICATE,
    GOSSIP_NEW_NODE,
    GOSSIP_NODE_DOWN,
    PING,
    NEW_BLOCK,
    NEW_TRANSACTION,
    AU_REVOIR,
    GET_BLOCKCHAIN,
    GET_BLOCK,
    PIN_BLOCK;
}
